
-- Create the registry table
create table public.registry (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text not null check (type in ('agent', 'token', 'project')),
  ticker text,
  contract_address text,
  description text,
  twitter text,
  website text,
  telegram text,
  tags text[] -- Array of strings
);

-- Enable Row Level Security (RLS)
alter table public.registry enable row level security;

-- Create Policy: Public Read Access
create policy "Enable read access for all users"
on public.registry for select
to anon
using (true);

-- Create Policy: Public Insert Access (for Agents)
create policy "Enable insert access for all users"
on public.registry for insert
to anon
with check (true);

-- Optional: Create an index on type for faster filtering
create index registry_type_idx on public.registry (type);
